### ISSUE TITLE
La punaise pour localiser le lieu de la conf est mal placee

### ISSUE THREAD

**Issue by mickaelistria** [snowcamp/snowcamp.github.io#10]
Le 41 rue de Mathematiques semble occuper un large espace dans Google Maps, si bien qu'il met la punaise a un endroit assez loin de ce que ce sera. Il vaut surement mieux utiliser les coordonnees GPS: https://www.google.fr/maps/place/45%C2%B011'34.1%22N+5%C2%B045'58.4%22E/@45.1927969,5.7656618,19z/data=!3m1!4b1!4m2!3m1!1s0x0:0x0?hl=en

**Comment by ctranxuan** [comment]
Fixed.
